package io.github.dejarol.azure.search.spark.connector.read.partitioning

/**
 * Search partition returned by a [[RangePartitioner]]
 * <br>
 * The filter generated by an instance of this class combines the values of the 2 sub filters
 * (<code>lowerBound</code> and <code>upperBound</code>)
 *  - if <code>lowerBound</code> is defined, it will generate a filter {{{
 *    field >= lowerBound
 *  }}}
 *  - if <code>upperBound</code> is defined, it will generate a filter {{{
 *    field < upperbound
 *  }}}
 * @param partitionId partition id
 * @param fieldName field name
 * @param lowerBound range lower bound (inclusive)
 * @param upperBound range upper bound (exclusive)
 */

case class RangePartition(
                           override protected val partitionId: Int,
                           private val fieldName: String,
                           private val lowerBound: Option[String],
                           private val upperBound: Option[String]
                         )
  extends AbstractSearchPartition(partitionId) {

  override def getPartitionFilter: String = {

    (lowerBound, upperBound) match {
      case (Some(l), Some(u)) => s"${getGeFilter(l)} and ${getLtFilter(u)}"
      case (Some(l), None) => getGeFilter(l)
      case (None, Some(u)) => s"${getLtFilter(u)} or $fieldName eq null"
      case (None, None) => null
    }
  }

  private def getGeFilter(value: String): String = s"$fieldName ge $value"

  private def getLtFilter(value: String) = s"$fieldName lt $value"
}

object RangePartition {

  /**
   * Create a collection of partitions
   * @param fieldName partition field name
   * @param values partition values
   * @return a collection of partitions
   */

  def createCollection(
                        fieldName: String,
                        values: Seq[String]
                      ): Seq[RangePartition] = {

    val lowerValues: Seq[Option[String]] = None +: values.map(Some(_))
    val upperValues: Seq[Option[String]] = values.map(Some(_)) :+ None

    // Zip lower values with upper values and create the partitions
    lowerValues.zip(upperValues).zipWithIndex.map {
      case ((lb, ub), index) =>
        RangePartition(index, fieldName, lb, ub)
    }
  }
}
