name: release
on:
  push:
    branches:
      - release/v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Set up JDK'
        uses: 'actions/setup-java@v4'
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: 'Set up sbt'
        uses: sbt/setup-sbt@v1
      - name: 'Release'
        shell: bash
        env:
          PGP_SECRET_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        run: |
          . devops/import_key.sh "$PGP_SECRET_KEY"
          gpg --list-keys